### ISSUE TITLE
Use vim.diagnostic.handlers rather than lsp publishDiagnostics handler

### ISSUE THREAD

**Issue by IndianBoy42** [chikko80/error-lens.nvim#1]
https://neovim.io/doc/user/diagnostic.html#diagnostic-handlers

this handles all kinds of diagnostics and not just lsps. it also means you don't have to override vim.diagnostic.config and in fact can just use it for configuration 

the idea comes from [lsp_lines.nvim](https://github.com/ErichDonGubler/lsp_lines.nvim)

**Comment by chikko80** [comment]
@IndianBoy42 
Thanks for the feedback!
Yeah like i said, i am not really familiar with lua, so appreciate your thoughts.

[https://github.com/chikko80/error-lens.nvim/blob/ad14fda7b4efeeeee719524ace440419f1eff342/lua/error-lens/init.lua](https://github.com/chikko80/error-lens.nvim/blob/ad14fda7b4efeeeee719524ace440419f1eff342/lua/error-lens/init.lua[](url))

I think i used to have this, but i changed it since its required a client in the setup function and i didn't want this, and had no clue how to do is besides this way

**Comment by IndianBoy42** [comment]
What's in that link is not what I'm talking about, maybe check out the lsp_lines.nvim setup function and the help docs I linked. It doesn't require a client. All LSPs and other diagnostics go through the vim.diagnostic API and you can register handlers there

Also, I wonder if you could/should leave rendering the virtual text to neovim core and just add the background highlighting to the line or even subpart of the line that the diagnostic is associated with

**Comment by chikko80** [comment]
The commit triggered some other issues, therefore i changed the code back to the old solution, but i'll take a look at lsp_lines in the future
