### ISSUE TITLE
Unusable with light themes

### ISSUE THREAD

**Issue by rbauduin** [chikko80/error-lens.nvim#4]
I regularly switch from dark to light color themes, and error-lens.nvim is only usable with dark color themes. Would be great to support both.

**Comment by rbauduin** [comment]
In case it can help anyone, I am using these options:
```
    opts = {
          auto_adjust = {
            enable = true,
            theme_bg = "#FFFFFF"
            step = 5, -- inc: colors should be brighter/darker
            total = 30 -- steps of blender
          },
    },
```
It is not great, but at least it is readable in both my dark and light themes.

**Comment by chikko80** [comment]
Hi,
can you share a screenshot of the problem?

**Comment by rbauduin** [comment]
Using a light theme, I have this result with default colors, where the code in error is not readable:
![image](https://github.com/chikko80/error-lens.nvim/assets/9960888/2b055fb6-20ba-48c6-9a24-bad49b667707)
Zooming on it:
![image](https://github.com/chikko80/error-lens.nvim/assets/9960888/c6f5e969-4715-4bb9-ad51-e1df43e378eb)

**Comment by chikko80** [comment]
I admit i could've explained it a bit better in the readme, but as of my knowledge, there is no standardized way to get the background color of a theme, cause every theme creator can use a different name for the colors. There are commonly used theme frameworks like the one NvChad uses - which provide a standardized name for the bg-color - but as soon as anyone uses another theme, these would break again.

Therefore you are responsible for setting the correct ```theme_bg``` code, if you use anything else than the default or at least dark themes. 

```lua
    auto_adjust = {
    enable = true,
    theme_bg = <your-theme-background-color-hex-code>
    step = 5, -- inc: colors should be brighter/darker
    total = 30 -- steps of blender
  },
```
But yeah that’s pretty much why there is the auto_adjust setting. It auto-adjusts the diagnostic colors since these are standardized but I couldn’t find any info about standardized background color names at the time of coding this.
So if you regularly switch that’s of course not optimal.

Just to clarify this, is your problem that the highlighted background of the line is dark or that the actual code in the line is grey?
Can you please set the correct ```theme_bg``` and post a screenshot again?

**Comment by rbauduin** [comment]
The problem in the screenshot for me is that the code is unreadable due to the combination of it being grey and the background being dark.
I'm using nvchad and am regularly switching between dark and light themes according to light conditions. I suppose that if you can't detect if the current theme is light or dark you can't solve this issue :-(
I'm working around by setting the auto_adjust with values that keep things readable with both light and dark themes:
![image](https://github.com/chikko80/error-lens.nvim/assets/9960888/e798a78e-6161-4e43-b66d-23f5718469e0)
and
![image](https://github.com/chikko80/error-lens.nvim/assets/9960888/5f685a19-4aa0-439a-946d-070459889996)
The result is not great, but at least I can use it with both color schemes.

**Comment by chikko80** [comment]
@rbauduin 
checkout the new branch, it doesn't solve this completely since i couldn't find any autocommand that triggers if nvchad changes the theme.
Therefore you need to quit and re-enter nvim in order to update the highlight groups but i hope that helps

**Comment by rbauduin** [comment]
This works great @chikko80 ! It works fine for me even without a restart.  Thanks for the fix :+1: , I hope you can merge it in the main branch.

**Comment by rbauduin** [comment]
Just FYI, I need a restart when I have the [Shade](https://github.com/sunjon/Shade.nvim) plugin active.
